---
version: "3.9"
services:
  backend:
    build:
      context: ./SpringBoot/.
      dockerfile: Dockerfile
    hostname: backend
    platform: linux/amd64`
    env_file:
      - stack.env
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  react-frontend:
    container_name: react-frontend
    build:
      context: ./react
      dockerfile: Dockerfile
      args:
        - VITE_GUMLOOP_BEARER_TOKEN=${VITE_GUMLOOP_BEARER_TOKEN}
        - BUILD_MODE=production
    env_file:
      - stack.env
    ports:
      - "8090:3000"
    
  python:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
