---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: db
      username: root
      password: pwd
      authentication-database: admin

application:
  client-origin-url: http://localhost:8090

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: https://dev-7k6npylc7qks07rv.us.auth0.com/
    audience: https://api.consensus.com
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}

application:
  client-origin-url: https://mchacks.benmusicgeek.synology.me

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

app:
  python-service:
    host: localhost
    port: 8000

  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: https://dev-7k6npylc7qks07rv.us.auth0.com/
    audience: https://api.consensus.com
